// Generated by CoffeeScript 2.3.1
(function() {
  var AMQP, amqpClient;

  AMQP = require('../bin/src/amqp');

  amqpClient = new AMQP({
    host: 'localhost'
  }, function(error) {
    // queue functinos can be chained
    return amqpClient.queue({
      name: 'testQueue'
    }).declare().bind('amq.direct', 'testRoutingKey', function() {
      var consumer, expectedMessages, recievedMessages;
      expectedMessages = 3;
      recievedMessages = 0;
      consumer = amqpClient.consume('testQueue', {}, function(message) {
        console.error("Got Message:", message.data);
        recievedMessages++;
        if (recievedMessages === expectedMessages) {
          console.error("Received all expected messages");
          return consumer.close(function() {
            console.error("Closed the consumer");
            return amqpClient.close(function() {
              return console.error("Closed the connection");
            });
          });
        }
      });
      amqpClient.publish('amq.direct', 'testRoutingKey', 'testMessage');
      amqpClient.publish('amq.direct', 'testRoutingKey', {
        json: 'this is a json object'
      });
      return amqpClient.publish('amq.direct', 'testRoutingKey', Buffer.alloc(3));
    });
  });

}).call(this);
