// Generated by CoffeeScript 2.3.1
(function() {
  var AMQP, amqpClient;

  AMQP = require('../bin/src/amqp');

  amqpClient = new AMQP({
    host: 'localhost'
  }, function(error) {
    // queue functinos can be chained
    return amqpClient.queue({
      name: 'testQueue'
    }).declare().bind('amq.direct', 'testRoutingKey', function() {
      return amqpClient.queue({
        name: 'testQueue2'
      }).declare().bind('amq.direct', 'testRoutingKey2', function() {
        var consumer;
        return consumer = amqpClient.consume('testQueue', {}, function(message) {
          console.error("Got Message:", message);
          return consumer.close();
        }, function() {});
      });
    });
  });

  // consumer = amqpClient.consume 'testQueue2', {}, (message)->
//   console.error "Got Message:", message

}).call(this);
