// Generated by CoffeeScript 2.3.1
(function() {
  var AMQP, amqpClient;

  AMQP = require('../bin/src/amqp');

  amqpClient = new AMQP({
    host: 'localhost'
  }, function(error) {
    // queue functinos can be chained
    return amqpClient.queue({
      name: 'testQueue'
    }).declare().bind('amq.direct', 'testRoutingKey', function() {
      return amqpClient.publish('amq.direct', 'testRoutingKey', 'testMessagewithConfirm', {
        confirm: true
      }, function(err, res) {
        var consumer;
        if (err != null) {
          return console.error("Message pushish error", err);
        }
        console.error("Message published");
        return consumer = amqpClient.consume('testQueue', {}, function(message) {
          console.error("Got Message:", message.data);
          return consumer.close(function() {
            console.error("Closed the consumer");
            return amqpClient.close(function() {
              return console.error("Closed the connection");
            });
          });
        });
      });
    });
  });

}).call(this);
